"""Reporter Agent — generates human-readable security report."""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Template

from scout import __version__
from scout.ai.prompts import AI_FIX_PROMPT
from scout.models import Finding

# Code-fence language hint per file extension (for Layer 2 prompt snippets).
LANGUAGE_BY_EXT = {
    ".py": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".java": "java",
    ".go": "go",
    ".rb": "ruby",
    ".php": "php",
    ".rs": "rust",
    ".c": "c",
    ".cpp": "cpp",
    ".h": "c",
    ".sh": "bash",
    ".bash": "bash",
    ".yml": "yaml",
    ".yaml": "yaml",
    ".json": "json",
}

# Fallback authoritative references when a finding carries none of its own.
DEFAULT_REFERENCES = {
    "secrets": ["https://owasp.org/www-community/vulnerabilities/Use_of_hard-coded_password"],
    "injection": ["https://owasp.org/www-community/Injection_Flaws"],
    "headers": ["https://owasp.org/www-project-secure-headers/"],
    "deps": ["https://owasp.org/www-community/vulnerabilities/Using_Components_with_Known_Vulnerabilities"],
}

REPORT_TEMPLATE = """\
# Security Report — {{ project_name }}

**Scanned:** {{ scan_date }}
**Files scanned:** {{ files_scanned }}
**Total issues:** {{ total_issues }}

---

## Executive Summary

{% if critical > 0 -%}
**Your app has {{ critical }} critical vulnerabilit{{ "y" if critical == 1 else "ies" }}.**
These must be fixed before shipping — they allow attackers to steal data,
impersonate users, or take over your server.
{% elif high > 0 -%}
**{{ high }} high-severity issue{{ "s" if high > 1 else "" }} found.**
Your app is at serious risk. Fix these in the next release.
{% elif medium > 0 -%}
**{{ medium }} medium-severity issue{{ "s" if medium > 1 else "" }} found.**
Not immediately exploitable, but these weaken your security posture.
{% else -%}
**{{ low }} low-severity issue{{ "s" if low > 1 else "" }} found.**
Minor improvements recommended but no urgent risk.
{% endif %}

| Severity | Count |
|----------|-------|
| 🔴 Critical | {{ critical }} |
| 🟠 High | {{ high }} |
| 🟡 Medium | {{ medium }} |
| 🔵 Low | {{ low }} |

---

## Fix Plan (Phased)

| Phase | What | Risk | Issues |
|-------|------|------|--------|
| 1 | Secrets, env vars, dependency bumps | Zero | {{ phase_counts.get(1, 0) }} |
| 2 | Security headers, CORS, rate limits | Low | {{ phase_counts.get(2, 0) }} |
| 3 | Auth & session fixes | Medium | {{ phase_counts.get(3, 0) }} |
| 4 | Injection & data layer | Medium-high | {{ phase_counts.get(4, 0) }} |
| 5 | Architecture changes | High | {{ phase_counts.get(5, 0) }} |

**How to apply:** Run `scout fix --phase 1` to start with zero-risk fixes.

---

## Issues

{% for finding in findings %}
### {{ loop.index }}. {{ severity_badge(finding.severity) }} {{ finding.title }}

**File:** `{{ finding.file }}:{{ finding.line }}`
**Phase:** {{ finding.fix_phase }} | **Scanner:** {{ finding.scanner }}

{{ finding.description }}

{% if finding.snippet %}
```
{{ finding.snippet }}
```
{% endif %}

**Fix:** {{ finding.fix_summary }}

---

{% endfor %}

## Next Steps

1. Review this report
2. Run `scout fix --phase 1` (zero-risk — secrets moved to .env, deps updated)
3. Test your app
4. Continue with `scout fix --phase 2` when ready
5. After fixes: `scout validate` to confirm issues are resolved

---

*Generated by [Scout](https://github.com/Varpost/Scout) — AI security team in a CLI.*
"""


def severity_badge(severity: str) -> str:
    """Return emoji badge for severity level."""
    return {
        "CRITICAL": "🔴",
        "HIGH": "🟠",
        "MEDIUM": "🟡",
        "LOW": "🔵",
    }.get(severity, "⚪")


def _slug(text: str) -> str:
    """Turn a finding title into a stable lowercase identifier slug."""
    slug = re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")
    return slug or "finding"


def _finding_id(finding: Finding) -> str:
    """Stable id for a finding, e.g. ``secrets/aws_access_key_detected``."""
    return f"{finding.scanner}/{_slug(finding.title)}"


def _language_for(file: str) -> str:
    """Markdown code-fence language hint for a file path (empty if unknown)."""
    return LANGUAGE_BY_EXT.get(Path(file).suffix.lower(), "")


def _references_for(finding: Finding) -> list[str]:
    """Return the finding's own references, or a scanner-level fallback."""
    if finding.references:
        return finding.references
    return DEFAULT_REFERENCES.get(finding.scanner, [])


def _relativize(findings: list[Finding], project_path: Path | None) -> None:
    """Rewrite each finding's file path relative to the project root, in place."""
    if not project_path:
        return
    for f in findings:
        try:
            f.file = str(Path(f.file).relative_to(project_path))
        except ValueError:
            pass


def generate_report(
    findings: list[Finding],
    output_path: Path,
    project_path: Path | None = None,
) -> None:
    """Generate a Markdown security report from findings.

    Args:
        findings: List of findings from the Scout agent.
        output_path: Where to write the report.
        project_path: Root of the scanned project (for display).
    """
    project_name = project_path.name if project_path else "Unknown Project"

    # Count severities
    critical = sum(1 for f in findings if f.severity == "CRITICAL")
    high = sum(1 for f in findings if f.severity == "HIGH")
    medium = sum(1 for f in findings if f.severity == "MEDIUM")
    low = sum(1 for f in findings if f.severity == "LOW")

    # Count per phase
    phase_counts: dict[int, int] = {}
    for f in findings:
        phase_counts[f.fix_phase] = phase_counts.get(f.fix_phase, 0) + 1

    _relativize(findings, project_path)

    template = Template(REPORT_TEMPLATE)
    template.globals["severity_badge"] = severity_badge

    report = template.render(
        project_name=project_name,
        scan_date=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        files_scanned="—",
        total_issues=len(findings),
        critical=critical,
        high=high,
        medium=medium,
        low=low,
        phase_counts=phase_counts,
        findings=findings,
    )

    output_path.write_text(report, encoding="utf-8")


def finding_to_dict(finding: Finding) -> dict[str, object]:
    """Serialize a single finding to the SCOUT_SPEC §4 Layer 3 JSON shape."""
    return {
        "id": _finding_id(finding),
        "scanner": finding.scanner,
        "file": finding.file,
        "line": finding.line,
        "severity": finding.severity,
        "fix_phase": finding.fix_phase,
        "code_snippet": finding.snippet,
        "title": finding.title,
        "explanation": finding.description,
        "fix_guidance": finding.fix_summary,
        "references": _references_for(finding),
    }


def generate_json(
    findings: list[Finding],
    output_path: Path | None = None,
    project_path: Path | None = None,
) -> str:
    """Render findings as machine-readable JSON (Layer 3).

    Args:
        findings: Findings from the Scout agent.
        output_path: If given, the JSON is also written here. If None, the
            JSON is only returned (e.g. for piping to stdout).
        project_path: Root of the scanned project (file paths are made relative).

    Returns:
        The JSON document as a string.
    """
    _relativize(findings, project_path)

    severity_counts: dict[str, int] = {}
    for f in findings:
        severity_counts[f.severity] = severity_counts.get(f.severity, 0) + 1

    payload = {
        "tool": "scout",
        "version": __version__,
        "project": project_path.name if project_path else None,
        "total_issues": len(findings),
        "severity_counts": severity_counts,
        "findings": [finding_to_dict(f) for f in findings],
    }

    text = json.dumps(payload, indent=2, ensure_ascii=False)
    if output_path:
        output_path.write_text(text + "\n", encoding="utf-8")
    return text


def generate_ai_prompts(
    findings: list[Finding],
    output_path: Path | None = None,
    project_path: Path | None = None,
) -> str:
    """Render findings as ready-to-paste AI fix prompts (Layer 2).

    Each finding becomes a self-contained prompt (SCOUT_SPEC §7) the user drops
    into their own AI assistant.

    Args:
        findings: Findings from the Scout agent.
        output_path: If given, the prompts are also written here.
        project_path: Root of the scanned project (file paths are made relative).

    Returns:
        The full prompt document as a string.
    """
    _relativize(findings, project_path)

    header = (
        "# Scout — AI Fix Prompts\n\n"
        "Paste each block below into your AI assistant (Cursor, Claude, Copilot, …). "
        "Each prompt is self-contained.\n"
    )

    if not findings:
        return header + "\nNo vulnerabilities found. Nothing to fix.\n"

    blocks: list[str] = []
    for index, finding in enumerate(findings, start=1):
        prompt = AI_FIX_PROMPT.format(
            file_path=finding.file,
            line_number=finding.line,
            title=finding.title,
            language=_language_for(finding.file),
            code_snippet=finding.snippet or "(snippet unavailable)",
            why_dangerous=finding.description,
            fix_steps=finding.fix_summary,
        )
        heading = f"## {index}. {severity_badge(finding.severity)} {finding.severity} — {finding.title}"
        blocks.append(f"{heading}\n\n{prompt}")

    document = header + "\n---\n\n" + "\n\n---\n\n".join(blocks) + "\n"
    if output_path:
        output_path.write_text(document, encoding="utf-8")
    return document
