"""Reporter Agent — generates human-readable security report."""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Template

from scout import __version__
from scout.ai.prompts import AI_FIX_PROMPT
from scout.models import Finding, Severity

# Code-fence language hint per file extension (for Layer 2 prompt snippets).
LANGUAGE_BY_EXT = {
    ".py": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".java": "java",
    ".go": "go",
    ".rb": "ruby",
    ".php": "php",
    ".rs": "rust",
    ".c": "c",
    ".cpp": "cpp",
    ".h": "c",
    ".sh": "bash",
    ".bash": "bash",
    ".yml": "yaml",
    ".yaml": "yaml",
    ".json": "json",
}

# Fallback authoritative references when a finding carries none of its own.
DEFAULT_REFERENCES = {
    "secrets": ["https://owasp.org/www-community/vulnerabilities/Use_of_hard-coded_password"],
    "injection": ["https://owasp.org/www-community/Injection_Flaws"],
    "headers": ["https://owasp.org/www-project-secure-headers/"],
    "deps": ["https://owasp.org/www-community/vulnerabilities/Using_Components_with_Known_Vulnerabilities"],
}

REPORT_TEMPLATE = """\
# Security Report — {{ project_name }}

**Scanned:** {{ scan_date }}
**Files scanned:** {{ files_scanned }}
**Total issues:** {{ total_issues }}

---

## Executive Summary

{% if critical > 0 -%}
**Your app has {{ critical }} critical vulnerabilit{{ "y" if critical == 1 else "ies" }}.**
These must be fixed before shipping — they allow attackers to steal data,
impersonate users, or take over your server.
{% elif high > 0 -%}
**{{ high }} high-severity issue{{ "s" if high > 1 else "" }} found.**
Your app is at serious risk. Fix these in the next release.
{% elif medium > 0 -%}
**{{ medium }} medium-severity issue{{ "s" if medium > 1 else "" }} found.**
Not immediately exploitable, but these weaken your security posture.
{% else -%}
**{{ low }} low-severity issue{{ "s" if low > 1 else "" }} found.**
Minor improvements recommended but no urgent risk.
{% endif %}

| Severity | Count |
|----------|-------|
| 🔴 Critical | {{ critical }} |
| 🟠 High | {{ high }} |
| 🟡 Medium | {{ medium }} |
| 🔵 Low | {{ low }} |

---

## Fix Plan (Phased)

| Phase | What | Risk | Issues |
|-------|------|------|--------|
| 1 | Secrets, env vars, dependency bumps | Zero | {{ phase_counts.get(1, 0) }} |
| 2 | Security headers, CORS, rate limits | Low | {{ phase_counts.get(2, 0) }} |
| 3 | Auth & session fixes | Medium | {{ phase_counts.get(3, 0) }} |
| 4 | Injection & data layer | Medium-high | {{ phase_counts.get(4, 0) }} |
| 5 | Architecture changes | High | {{ phase_counts.get(5, 0) }} |

**How to apply:** Run `scout scan <path> --format ai-prompt` to turn every issue below into a
ready-to-paste fix prompt for your AI assistant. Start with Phase 1 — those fixes are zero-risk.

---

## Issues

{% for finding in findings %}
### {{ loop.index }}. {{ severity_badge(finding.severity) }} {{ finding.title }}

**File:** `{{ finding.file }}:{{ finding.line }}`
**Phase:** {{ finding.fix_phase }} | **Scanner:** {{ finding.scanner }}

{{ finding.description }}

{% if finding.snippet %}
```
{{ finding.snippet }}
```
{% endif %}

**Fix:** {{ finding.fix_summary }}

---

{% endfor %}

## Next Steps

1. Review this report
2. Run `scout scan <path> --format ai-prompt` for ready-to-paste fix prompts (start with Phase 1 — zero-risk)
3. Apply the fixes with your AI assistant (Cursor, Claude, Copilot, …)
4. Test your app
5. Re-run `scout scan` to verify the issues are gone

---

*Generated by [Scout](https://github.com/Varpost/Scout) — AI security team in a CLI.*
"""


# Keyed off the canonical Severity enum — see models.Severity.
_SEVERITY_BADGES: dict[str, str] = {
    Severity.CRITICAL.value: "🔴",
    Severity.HIGH.value: "🟠",
    Severity.MEDIUM.value: "🟡",
    Severity.LOW.value: "🔵",
}


def severity_badge(severity: str) -> str:
    """Return emoji badge for severity level."""
    return _SEVERITY_BADGES.get(severity, "⚪")


def _slug(text: str) -> str:
    """Turn a finding title into a stable lowercase identifier slug."""
    slug = re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")
    return slug or "finding"


def _finding_id(finding: Finding) -> str:
    """Stable id for a finding, e.g. ``secrets/aws_access_key_detected``."""
    return f"{finding.scanner}/{_slug(finding.title)}"


def _language_for(file: str) -> str:
    """Markdown code-fence language hint for a file path (empty if unknown)."""
    return LANGUAGE_BY_EXT.get(Path(file).suffix.lower(), "")


def _references_for(finding: Finding) -> list[str]:
    """Return the finding's own references, or a scanner-level fallback."""
    if finding.references:
        return finding.references
    return DEFAULT_REFERENCES.get(finding.scanner, [])


def _relativize(findings: list[Finding], project_path: Path | None) -> None:
    """Rewrite each finding's file path relative to the project root, in place."""
    if not project_path:
        return
    for f in findings:
        try:
            f.file = str(Path(f.file).relative_to(project_path))
        except ValueError:
            pass


def generate_report(
    findings: list[Finding],
    output_path: Path,
    project_path: Path | None = None,
    files_scanned: int | None = None,
) -> None:
    """Generate a Markdown security report from findings.

    Args:
        findings: List of findings from the Scout agent.
        output_path: Where to write the report.
        project_path: Root of the scanned project (for display).
        files_scanned: Number of files the scan actually covered.
    """
    project_name = project_path.name if project_path else "Unknown Project"

    counts = {sev: sum(1 for f in findings if f.severity == sev.value) for sev in Severity}

    # Count per phase
    phase_counts: dict[int, int] = {}
    for f in findings:
        phase_counts[f.fix_phase] = phase_counts.get(f.fix_phase, 0) + 1

    _relativize(findings, project_path)

    template = Template(REPORT_TEMPLATE)
    template.globals["severity_badge"] = severity_badge

    report = template.render(
        project_name=project_name,
        scan_date=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        files_scanned=files_scanned if files_scanned is not None else "—",
        total_issues=len(findings),
        critical=counts[Severity.CRITICAL],
        high=counts[Severity.HIGH],
        medium=counts[Severity.MEDIUM],
        low=counts[Severity.LOW],
        phase_counts=phase_counts,
        findings=findings,
    )

    output_path.write_text(report, encoding="utf-8")


def finding_to_dict(finding: Finding) -> dict[str, object]:
    """Serialize a single finding to the SCOUT_SPEC §4 Layer 3 JSON shape."""
    return {
        "id": _finding_id(finding),
        "scanner": finding.scanner,
        "file": finding.file,
        "line": finding.line,
        "severity": finding.severity,
        "fix_phase": finding.fix_phase,
        "code_snippet": finding.snippet,
        "title": finding.title,
        "explanation": finding.description,
        "fix_guidance": finding.fix_summary,
        "references": _references_for(finding),
    }


def generate_json(
    findings: list[Finding],
    output_path: Path | None = None,
    project_path: Path | None = None,
    files_scanned: int | None = None,
) -> str:
    """Render findings as machine-readable JSON (Layer 3).

    Args:
        findings: Findings from the Scout agent.
        output_path: If given, the JSON is also written here. If None, the
            JSON is only returned (e.g. for piping to stdout).
        project_path: Root of the scanned project (file paths are made relative).
        files_scanned: Number of files the scan actually covered.

    Returns:
        The JSON document as a string.
    """
    _relativize(findings, project_path)

    severity_counts: dict[str, int] = {}
    for f in findings:
        severity_counts[f.severity] = severity_counts.get(f.severity, 0) + 1

    payload = {
        "tool": "scout",
        "version": __version__,
        "project": project_path.name if project_path else None,
        "files_scanned": files_scanned,
        "total_issues": len(findings),
        "severity_counts": severity_counts,
        "findings": [finding_to_dict(f) for f in findings],
    }

    text = json.dumps(payload, indent=2, ensure_ascii=False)
    if output_path:
        output_path.write_text(text + "\n", encoding="utf-8")
    return text


# GitHub Code Scanning displays "error" prominently on PRs; "note" stays quiet.
_SARIF_LEVELS: dict[str, str] = {
    Severity.CRITICAL.value: "error",
    Severity.HIGH.value: "error",
    Severity.MEDIUM.value: "warning",
    Severity.LOW.value: "note",
}
# GitHub's severity badge/sort key (CVSS-like 0-10 string).
_SARIF_SECURITY_SEVERITY: dict[str, str] = {
    Severity.CRITICAL.value: "9.5",
    Severity.HIGH.value: "8.0",
    Severity.MEDIUM.value: "5.5",
    Severity.LOW.value: "3.0",
}


def _sarif_uri(file: str, project_path: Path | None) -> str:
    """Repo-relative POSIX URI for a finding's file (SARIF artifactLocation)."""
    path = Path(file)
    if project_path:
        try:
            path = path.relative_to(project_path)
        except ValueError:
            pass
    return path.as_posix()


def generate_sarif(
    findings: list[Finding],
    output_path: Path | None = None,
    project_path: Path | None = None,
    files_scanned: int | None = None,
) -> str:
    """Render findings as SARIF 2.1.0 for GitHub Code Scanning.

    Args:
        findings: Findings from the Scout agent.
        output_path: If given, the SARIF is also written here. If None, the
            document is only returned (e.g. for piping to stdout).
        project_path: Root of the scanned project (URIs are made relative).
        files_scanned: Number of files the scan actually covered.

    Returns:
        The SARIF document as a string.
    """
    rules: list[dict[str, object]] = []
    rule_index: dict[str, int] = {}
    results: list[dict[str, object]] = []

    for finding in findings:
        fid = _finding_id(finding)
        if fid not in rule_index:
            rule_index[fid] = len(rules)
            rule: dict[str, object] = {
                "id": fid,
                "name": finding.title,
                "shortDescription": {"text": finding.title},
                "fullDescription": {"text": finding.description},
                "defaultConfiguration": {"level": _SARIF_LEVELS.get(finding.severity, "warning")},
                "properties": {
                    "tags": ["security"],
                    "security-severity": _SARIF_SECURITY_SEVERITY.get(finding.severity, "5.5"),
                },
            }
            if finding.fix_summary:
                rule["help"] = {"text": finding.fix_summary}
            references = _references_for(finding)
            if references:
                rule["helpUri"] = references[0]
            rules.append(rule)

        results.append(
            {
                "ruleId": fid,
                "ruleIndex": rule_index[fid],
                "level": _SARIF_LEVELS.get(finding.severity, "warning"),
                "message": {"text": f"{finding.title}: {finding.description}"},
                "locations": [
                    {
                        "physicalLocation": {
                            "artifactLocation": {
                                "uri": _sarif_uri(finding.file, project_path),
                                "uriBaseId": "%SRCROOT%",
                            },
                            # Project-level findings carry synthetic anchors —
                            # SARIF requires startLine >= 1.
                            "region": {"startLine": max(1, finding.line)},
                        }
                    }
                ],
            }
        )

    run: dict[str, object] = {
        "tool": {
            "driver": {
                "name": "Scout",
                "informationUri": "https://github.com/Varpost/Scout",
                "version": __version__,
                "rules": rules,
            }
        },
        "results": results,
    }
    if files_scanned is not None:
        run["properties"] = {"filesScanned": files_scanned}

    payload = {
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [run],
    }
    text = json.dumps(payload, indent=2, ensure_ascii=False)
    if output_path:
        output_path.write_text(text + "\n", encoding="utf-8")
    return text


def generate_ai_prompts(
    findings: list[Finding],
    output_path: Path | None = None,
    project_path: Path | None = None,
) -> str:
    """Render findings as ready-to-paste AI fix prompts (Layer 2).

    Each finding becomes a self-contained prompt (SCOUT_SPEC §7) the user drops
    into their own AI assistant.

    Args:
        findings: Findings from the Scout agent.
        output_path: If given, the prompts are also written here.
        project_path: Root of the scanned project (file paths are made relative).

    Returns:
        The full prompt document as a string.
    """
    _relativize(findings, project_path)

    header = (
        "# Scout — AI Fix Prompts\n\n"
        "Paste each block below into your AI assistant (Cursor, Claude, Copilot, …). "
        "Each prompt is self-contained.\n"
    )

    if not findings:
        return header + "\nNo vulnerabilities found. Nothing to fix.\n"

    blocks: list[str] = []
    for index, finding in enumerate(findings, start=1):
        prompt = AI_FIX_PROMPT.format(
            file_path=finding.file,
            line_number=finding.line,
            title=finding.title,
            language=_language_for(finding.file),
            code_snippet=finding.snippet or "(snippet unavailable)",
            why_dangerous=finding.description,
            fix_steps=finding.fix_summary,
        )
        heading = f"## {index}. {severity_badge(finding.severity)} {finding.severity} — {finding.title}"
        blocks.append(f"{heading}\n\n{prompt}")

    document = header + "\n---\n\n" + "\n\n---\n\n".join(blocks) + "\n"
    if output_path:
        output_path.write_text(document, encoding="utf-8")
    return document
